name: Merge data → main

on:
  push:
    branches:
      - data

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"

      - name: Merge data into main (auto-resolve CSV conflicts)
        run: |
          set +e
          git fetch origin data:data
          git merge data --no-ff -m "CI: merge updated leaderboard.csv"
          if [ $? -ne 0 ]; then
            echo "Conflict detected – using data branch's CSV"
            git checkout --theirs leaderboard.csv
            git add leaderboard.csv
            git commit -m "CI: resolve CSV conflict by taking data version"
          fi

      - name: Push to main
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
