name: Merge data → main

# Trigger on every push to the data branch
on:
  push:
    branches:
      - data

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out both branches with full history
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0            # retrieve full git history
          ref: main                 # start from main

      # 2. Configure Git with a bot identity
      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"

      # 3. Merge the incoming data changes
      - name: Merge data into main
        run: |
          # add the data branch as a remote ref
          git fetch origin data:data
          git merge data --no-ff -m "CI: merge updated leaderboard.csv"

      # 4. Push the merge commit back to main
      - name: Push to main
        run: |
          git push origin main
        env:
          # uses the injected GITHUB_TOKEN with write permissions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
